In [17]:
#!pip install scikit-learn

In [5]:
import numpy as np
import pandas as pd
#Data Visulization
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import seaborn as sns
%matplotlib inline 

In [6]:
df1=pd.read_csv('C:/Users/Admin/Downloads/archive (2)/creditcard.csv')
df=df1.drop(range(61000,284806))
df.head()
x=df.iloc[:,0:30].values
y=df.iloc[:,30].values

In [13]:
x

array([[ 0.00000000e+00, -1.35980713e+00, -7.27811730e-02, ...,
         1.33558377e-01, -2.10530530e-02,  1.49620000e+02],
       [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01, ...,
        -8.98309900e-03,  1.47241690e-02,  2.69000000e+00],
       [ 1.00000000e+00, -1.35835406e+00, -1.34016307e+00, ...,
        -5.53527940e-02, -5.97518410e-02,  3.78660000e+02],
       ...,
       [ 4.96030000e+04, -1.22331049e+00,  1.14794118e+00, ...,
        -8.91250170e-02, -2.68532092e-01,  3.91000000e+00],
       [ 4.96040000e+04, -1.48250936e+00,  1.36595655e+00, ...,
        -3.51633028e-01, -9.75502110e-02,  4.85700000e+01],
       [ 1.72792000e+05, -5.33412522e-01, -1.89733337e-01, ...,
        -2.41530900e-03,  1.36489140e-02,  2.17000000e+02]])

In [14]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
df.shape

(61001, 31)

In [16]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [66]:
df.info()

In [67]:
df.describe()

In [17]:
#MISSING VALUES
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [8]:
#Feature scaling 
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [20]:
#Fitiing logistic regression to the training set 
from sklearn.linear_model import LogisticRegression
Classifier = LogisticRegression(random_state=0)
Classifier.fit(x_train,y_train)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [21]:
#Predicting the test results
from sklearn.metrics import accuracy_score
y_pred = Classifier.predict(x_test)
print("Accuracy Score: ",accuracy_score(y_test,y_pred))
# Accuracy Score:  0.9978757768336786 = Approx 99.79%

Accuracy Score:  0.9976231456437997


In [9]:
def evaluate_model(model, x_test, y_test):
    from sklearn import metrics

    # Predict Test Data 
    y_pred = model.predict(x_test)

    # Calculate accuracy, precision, recall, f1-score, and kappa score
    acc = metrics.accuracy_score(y_test, y_pred)
    prec = metrics.precision_score(y_test, y_pred)
    rec = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    kappa = metrics.cohen_kappa_score(y_test, y_pred)

    # Calculate area under curve (AUC)
    y_pred_proba = model.predict_proba(x_test)[::,1]
    fpr, tpr, _ = metrics.roc_curve(y_test, y_pred_proba)
    auc = metrics.roc_auc_score(y_test, y_pred_proba)

    # Display confussion matrix
    cm = metrics.confusion_matrix(y_test, y_pred)

    return {'acc': acc, 'prec': prec, 'rec': rec, 'f1': f1, 'kappa': kappa, 
            'fpr': fpr, 'tpr': tpr, 'auc': auc, 'cm': cm}

In [64]:
from sklearn import tree

# Building Decision Tree model 
dtc = tree.DecisionTreeClassifier(random_state=0)
dtc.fit(x_train, y_train)

# Evaluate Model
dtc_eval = evaluate_model(dtc, x_test, y_test)

# Print result
print('Accuracy:', dtc_eval['acc'])
print('Precision:', dtc_eval['prec'])
print('Recall:', dtc_eval['rec'])
print('F1 Score:', dtc_eval['f1'])
print('Cohens Kappa Score:', dtc_eval['kappa'])
print('Area Under Curve:', dtc_eval['auc'])
print('Confusion Matrix:\n', dtc_eval['cm'])

Accuracy: 0.9980162213405428
Precision: 0.4625
Recall: 0.7326732673267327
F1 Score: 0.5670498084291188
Cohens Kappa Score: 0.566106554321532
Area Under Curve: 0.8655804035583735
Confusion Matrix:
 [[56775    86]
 [   27    74]]


In [23]:
from sklearn.ensemble import RandomForestClassifier

#Building Random Forest Classifier model
clf=RandomForestClassifier(n_estimators=100)
clf.fit(x_train,y_train)

# Evaluate Model
clf_eval = evaluate_model(clf,x_test,y_test)

#Print result
print('Accuracy:', clf_eval['acc'])
print('Precision:', clf_eval['prec'])
print('Recall:', clf_eval['rec'])
print('F1 Score:', clf_eval['f1'])
print('Cohens Kappa Score:', clf_eval['kappa'])
print('Area Under Curve:', clf_eval['auc'])
print('Confusion Matrix:\n', clf_eval['cm'])

Accuracy: 0.9995082370297517
Precision: 0.9722222222222222
Recall: 0.875
F1 Score: 0.9210526315789473
Cohens Kappa Score: 0.9208066672724676
Area Under Curve: 0.9742208699942438
Confusion Matrix:
 [[12160     1]
 [    5    35]]


In [25]:
from sklearn import svm

#Building SVM model
cls=svm.SVC(kernel='linear',probability=True)
cls.fit(x_train,y_train)

#Evaluate Model
cls_eval = evaluate_model(cls,x_test,y_test)

#Print result
print('Accuracy:', cls_eval['acc'])
print('Precision:', cls_eval['prec'])
print('Recall:', cls_eval['rec'])
print('F1 Score:', cls_eval['f1'])
print('Cohens Kappa Score:', cls_eval['kappa'])
print('Area Under Curve:', cls_eval['auc'])
print('Confusion Matrix:\n', cls_eval['cm'])

Accuracy: 0.9980329481190067
Precision: 0.7105263157894737
Recall: 0.675
F1 Score: 0.6923076923076923
Cohens Kappa Score: 0.6913216632688127
Area Under Curve: 0.9886419702327112
Confusion Matrix:
 [[12150    11]
 [   13    27]]


In [27]:
!pip install xgboost

In [10]:
import xgboost as xgb
#Building xgboost model
xgb_cl=xgb.XGBClassifier()
xgb_cl.fit(x_train,y_train)

#Evaluate Model
xgb_cl_eval=evaluate_model(xgb_cl,x_test,y_test)

#Print result
print('Accuracy:', xgb_cl_eval['acc'])
print('Precision:', xgb_cl_eval['prec'])
print('Recall:', xgb_cl_eval['rec'])
print('F1 Score:', xgb_cl_eval['f1'])
print('Cohens Kappa Score:', xgb_cl_eval['kappa'])
print('Area Under Curve:', xgb_cl_eval['auc'])
print('Confusion Matrix:\n', xgb_cl_eval['cm'])

Accuracy: 0.9996721580198344
Precision: 0.9736842105263158
Recall: 0.925
F1 Score: 0.9487179487179489
Cohens Kappa Score: 0.9485536105448021
Area Under Curve: 0.9961763012910122
Confusion Matrix:
 [[12160     1]
 [    3    37]]


In [11]:
!pip install catboost

In [12]:
import catboost as ctb
#Building catboost model
cbc=ctb.CatBoostClassifier()
cbc.fit(x_train,y_train)

#Evaluate model
cbc_eval=evaluate_model(cbc,x_test,y_test)

#Print result
print('Accuracy:', cbc_eval['acc'])
print('Precision:', cbc_eval['prec'])
print('Recall:', cbc_eval['rec'])
print('F1 Score:', cbc_eval['f1'])
print('Cohens Kappa Score:', cbc_eval['kappa'])
print('Area Under Curve:', cbc_eval['auc'])
print('Confusion Matrix:\n', cbc_eval['cm'])

Learning rate set to 0.054186
0:	learn: 0.5117400	total: 184ms	remaining: 3m 3s
1:	learn: 0.3863595	total: 215ms	remaining: 1m 47s
2:	learn: 0.2912389	total: 236ms	remaining: 1m 18s
3:	learn: 0.2147257	total: 252ms	remaining: 1m 2s
4:	learn: 0.1619664	total: 268ms	remaining: 53.3s
5:	learn: 0.1190368	total: 293ms	remaining: 48.5s
6:	learn: 0.0903365	total: 308ms	remaining: 43.7s
7:	learn: 0.0691619	total: 328ms	remaining: 40.7s
8:	learn: 0.0531140	total: 349ms	remaining: 38.4s
9:	learn: 0.0408926	total: 370ms	remaining: 36.6s
10:	learn: 0.0325303	total: 396ms	remaining: 35.6s
11:	learn: 0.0260348	total: 415ms	remaining: 34.2s
12:	learn: 0.0212143	total: 442ms	remaining: 33.5s
13:	learn: 0.0177936	total: 464ms	remaining: 32.6s
14:	learn: 0.0148126	total: 479ms	remaining: 31.5s
15:	learn: 0.0125786	total: 495ms	remaining: 30.4s
16:	learn: 0.0107473	total: 509ms	remaining: 29.4s
17:	learn: 0.0092141	total: 525ms	remaining: 28.7s
18:	learn: 0.0081439	total: 540ms	remaining: 27.9s
19:	learn